- name: clone repo
  git:
    repo: "https://mflis:{{ github_token }}@github.com/mflis/sentiment-analysis.git"
    dest: ~/sentiment-analysis
    force: yes

- name: create directories
  file:
    path: "~/sentiment-analysis/{{item}}"
    state: directory
  with_items:
    - data/glove
    - results/logs
    - sacred-logs

- name: Unarchive glove data
  unarchive:
    src: http://nlp.stanford.edu/data/glove.6B.zip
    dest: ~/sentiment-analysis/data/glove
    creates: ~/sentiment-analysis/data/glove/glove.6B.50d.txt
    remote_src: yes

- name: install helper packages
  become: true
  yum:
    name: "{{ item  }}"
    state: present
  with_items:
    - htop
    - tree

- name: install dependencies
  become: yes
  pip:
   requirements: /home/ec2-user/sentiment-analysis/requirements.txt

- name: make balanced set
  command: python3 ~/sentiment-analysis/src/balanced_set.py
  args:
    chdir: ~/sentiment-analysis
    creates: /home/ec2-user/sentiment-analysis/data/balanced-reviews.csv

