- name: Launch new instance
  ec2:
    spot_price: 0.90
    spot_wait_timeout: 600
    keypair: "{{ aws_keypair}}"
    group_id: "{{aws_security_group}}"
    instance_type:  "{{aws_instance_type}}"
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    image: "{{ aws_ami_image }}"
    region:  "{{ aws_region }}"
    zone: "{{ aws_zone  }}"
    wait: yes
    wait_timeout: 500
    instance_tags:
      instance_type: tensorflow
    count_tag: instance_type
  register: ec2

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: launched
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"
