- name: ensure local fetch directory exists
  local_action:
      module: file
      path: "{{ fetch_dir }}"
      state: directory

- synchronize:
    src: ~/sentiment-analysis/results/
    dest:  "{{ fetch_dir }}"
    mode: pull