- name: Fetch results
  hosts: launched
  gather_facts: False

  tasks:
    - synchronize:
        src: ~/sentiment-analysis/results
        dest: ~/PycharmProjects/tensorflow-playgound/remote-results-tf-idf-batch-new
        mode: pull
