- name: Fetch results
  hosts: all
  gather_facts: False

  tasks:
    - synchronize:
        src: ~/sentiment-analysis/results/
        dest: "~/PycharmProjects/tensorflow-playgound/remote-results/{{ fetch_dir }}"
        mode: pull
