- name: Launch spot instance
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Launch new instance
      ec2:
        spot_price: 0.90
        spot_wait_timeout: 600
        keypair: deep-test
        group_id: sg-506a4523
        instance_type: p2.xlarge
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        image: ami-4716b23d
        exact_count: 1
        region: us-east-1
        zone: us-east-1a
        wait: yes
        wait_timeout: 500
        instance_tags:
          foo: bar
        count_tag: foo
      register: ec2

    - debug:
        var: ec2
#    - name: Add new instance to host group
#      add_host:
#        hostname: "{{ item.public_ip }}"
#        groupname: launched
#      with_items: "{{ ec2.instances }}"
#
#    - name: Wait for SSH to come up
#      wait_for:
#        host: "{{ item.public_dns_name }}"
#        port: 22
#        delay: 60
#        timeout: 320
#        state: started
#      with_items: "{{ ec2.instances }}"
