- name: Prepare environment
  hosts: all
  gather_facts: False
  tasks:
    - name: clone repo
      git:
        repo: "https://mflis:{{ github_token }}@github.com/mflis/sentiment-analysis.git"
        dest: ~/sentiment-analysis
        force: yes

    - name: create directories
      file:
        path: "{{item}}"
        state: directory
      with_items:
        - ~/sentiment-analysis/data/glove
        - ~/sentiment-analysis/results/checkpoints
        - ~/sentiment-analysis/results/logs

    - name: Unarchive glove data
      unarchive:
        src: http://nlp.stanford.edu/data/glove.6B.zip
        dest: ~/sentiment-analysis/data/glove
        creates: ~/sentiment-analysis/data/glove/glove.6B.50d.txt
        remote_src: yes

    - name: install tree
      become: true
      yum:
        name: tree
        state: present

    - name: make balanced set
      command: bash ~/sentiment-analysis/balanced-set.sh
      args:
        chdir: ~/sentiment-analysis
        creates: /home/ec2-user/sentiment-analysis/data/balanced-reviews.csv


    - name: install dependencies
      become: yes
      pip:
       requirements: /home/ec2-user/sentiment-analysis/requirements.txt
