- name: Run experiment
  hosts: all
  gather_facts: False
  tasks:
    - name: Run tensorflow
      command: python3 src/amazon-tfidf.py with full_config_tfidf.yaml  --file_storage="results/sacred-logs/{{item.0}}"
      args:
        chdir: /home/ec2-user/sentiment-analysis
      delegate_to: "{{item.0}}"
      async: 10000
      poll: 60
      with_items:
        - "{{ groups['all'] }}"
