- name: Prepare environment
  hosts: all
  gather_facts: False
  tasks:
#no obersvers in run
    - name: Run tensorflow
      command: python3 src/cnn_network.py with full_config.yaml 'epochs=100' 'batch_size=4096'
      args:
        chdir: /home/ec2-user/sentiment-analysis
      async: 10000
      poll: 60
